# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.weather_manager:
            class:     AppBundle\Manager\WeatherManager
            arguments: ['@service_container']

    app.image_manager:
            class:     AppBundle\Manager\ImageManager
            arguments: ['@service_container']