app_user_create:
    pattern: /create
    defaults: { _controller: AppBundle:Api:create }
    requirements:
        _method: POST

app_user_login:
    pattern: /login
    defaults: { _controller: AppBundle:Api:login }
    requirements:
        _method: POST

app_image_upload:
    pattern: /image
    defaults: { _controller: AppBundle:Api:image }
    requirements:
        _method: POST

app_all:
    pattern: /all
    defaults: { _controller: AppBundle:Api:all }
    requirements:
        _method: GET

app_image_gif:
    pattern: /gif
    defaults: { _controller: AppBundle:Api:gif }
    requirements:
        _method: GET