app_user_create:
    pattern: /login
    defaults: { _controller: AppBundle:User:login }
    requirements:
        _method: POST

app_image_upload:
    pattern: /image
    defaults: { _controller: AppBundle:User:image }
    requirements:
        _method: POST

app_all:
    pattern: /all
    defaults: { _controller: AppBundle:User:all }
    requirements:
        _method: GET

app_image_gif:
    pattern: /gif
    defaults: { _controller: AppBundle:User:gif }
    requirements:
        _method: GET